[versions]
kotlin = "2.2.0"
agp = "8.12.1"
spotless = "7.2.1"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
com-kenkoro-android-application = { id = "com.kenkoro.android.application" }
com-kenkoro-android-application-flavors = { id = "com.kenkoro.android.application.flavors" }
com-kenkoro-android-application-formatting = { id = "com.kenkoro.android.application.formatting" }